-- Populando Banco

INSERT INTO BANCO(NOME) VALUES('Banco do Brasil');
INSERT INTO BANCO(NOME) VALUES('Caixa Econômica Federal');
INSERT INTO BANCO(NOME) VALUES('Bradesco');
INSERT INTO BANCO(NOME) VALUES('NuConta');

-- Populando Agências

INSERT INTO AGENCIA(NOME, NUMERO, BANCO_ID) 
VALUES('Banco do Brasil Centro', '1234-5', 1);
INSERT INTO AGENCIA(NOME, NUMERO, BANCO_ID) 
VALUES('Banco do Brasil Sul', '6789-0', 1);

INSERT INTO AGENCIA(NOME, NUMERO, BANCO_ID) 
VALUES('Caixa Av. Miguel Rosa', '1234-5', 2);
INSERT INTO AGENCIA(NOME, NUMERO, BANCO_ID) 
VALUES('Caixa Av. Frei Serafim', '6789-0', 2);

-- Populando Cliente

INSERT INTO CLIENTE(NOME, CPF) 
VALUES('Gleison Andrade', '048.121.863-74');

-- Populando Conta

INSERT INTO CONTA(NUMERO, SALDO, SENHA, TIPO, AGENCIA_ID, CLIENTE_ID) 
VALUES('00000-0', 10.0, '123456', 'CORRENTE', 1, 1);

-- Populando Extrato
-- YYYY-MM-DD HH:MI:SS
INSERT INTO EXTRATO(DATA, TIPO_OPERACAO, VALOR, CONTA_ID, INFORMACOES) 
VALUES('2019-04-06 12:00:00', 'DEPOSITO', 10.0, 1, 'Depósito no valor de R$ 10,00');

